spring:
  application:
    name: MongoSpringBoot
  data:
    mongodb:
      uri: mongodb://localhost:28017/mongospring?replicaSet=rs0&directConnection=true&w=majority
      database: mongospring
  cloud:
    function:
      definition: messageConsumer;outletConsumer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        messageConsumer-in-0:
          destination: spring.mongo.message
          group: nfo-MongoSpringBoot-group
        outletConsumer-in-0:
          destination: spring.mongo.outlet
          group: nfo-MongoSpringBoot-group
mongock:
  migration-scan-package: com.MongoSpringBoot.config.dbmigrations

server:
  port: 8080
debug: true