name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up java 21
        uses: actions/setup-java@v4 
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start Infrastructure
        run: docker compose -f DockerCompose/docker-compose.yaml up -d

      - name: Wait for Services to Start
        run: |
          echo "Waiting for Mongo and Kafka to initialize..."
          sleep 30
          # FIX 2: Added -f path here so it checks the right containers
          docker compose -f DockerCompose/docker-compose.yaml ps

      - name: Run Maven Unit Tests
        working-directory: ./MongoSpringBoot
        run: mvn clean test 

      - name: Print Logs on Failure
        if: failure()
        run: docker compose -f DockerCompose/docker-compose.yaml logs

      - name: Stop Containers
        if: always()
        run: docker compose -f DockerCompose/docker-compose.yaml down

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: unit-tests

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR
        working-directory: ./MongoSpringBoot
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./MongoSpringBoot
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
            ${{ secrets.DOCKER_USERNAME }}/my-spring-app:${{ github.sha }}