name: Step 1 - CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up java 21
        uses: actions/setup-java@v4 
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start Infrastructure
        run: docker compose -f DockerCompose/docker-compose.yml up -d

      - name: Wait for Services to Start
        run: |
          echo "Waiting for Mongo and Kafka to initialize..."
          sleep 30
          # FIX 2: Added -f path here so it checks the right containers
          docker compose -f DockerCompose/docker-compose.yml ps

      - name: Run Maven Unit Tests
        working-directory: ./MongoSpringBoot
        run: mvn clean test 

      - name: Print Logs on Failure
        if: failure()
        run: docker compose -f DockerCompose/docker-compose.yml logs

      - name: Stop Containers
        if: always()
        run: docker compose -f DockerCompose/docker-compose.yml down